---
plugin: aws_ec2
regions:
 - us-east-1

# target only specific servers
# filters:
#   tag:Name: dev*

# create dynamic groups
keyed_groups:
  - key: tags
  - key: instance_type
    prefix: instance_type